//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionVolume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdmissionVolume()
        {
            this.DistributedAdmissionVolume = new HashSet<DistributedAdmissionVolume>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<int> EducationLevelId { get; set; }
        public Nullable<int> DirectionId { get; set; }
        public Nullable<int> NumberBudgetO { get; set; }
        public Nullable<int> NumberBudgetZ { get; set; }
        public Nullable<int> NumberBudgetOZ { get; set; }
        public Nullable<int> NumberPaidO { get; set; }
        public Nullable<int> NumberPaidZ { get; set; }
        public Nullable<int> NumberPaidOZ { get; set; }
        public Nullable<int> NumberQuotaO { get; set; }
        public Nullable<int> NumberQuotaZ { get; set; }
        public Nullable<int> NumberQuotaOZ { get; set; }
        public Nullable<int> NumberTargetO { get; set; }
        public Nullable<int> NumberTargetZ { get; set; }
        public Nullable<int> NumberTargetOZ { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributedAdmissionVolume> DistributedAdmissionVolume { get; set; }
    }
}
