//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildVersion
    {
        public int Id { get; set; }
        public string Version { get; set; }
        public string ChangeList { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
