//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignIndividualAchievement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CampaignIndividualAchievement()
        {
            this.EntranceIndividualAchievements = new HashSet<EntranceIndividualAchievement>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public string Name { get; set; }
        public Nullable<int> IndividualAchievementCategoryId { get; set; }
        public Nullable<int> MaxMark { get; set; }
        public string ExportCode { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual IndividualAchievementCategory IndividualAchievementCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntranceIndividualAchievement> EntranceIndividualAchievements { get; set; }
    }
}
