//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaign()
        {
            this.AdmissionVolumes = new HashSet<AdmissionVolume>();
            this.CampaignIndividualAchievements = new HashSet<CampaignIndividualAchievement>();
            this.CompetitiveGroups = new HashSet<CompetitiveGroup>();
            this.EntranceTests = new HashSet<EntranceTest>();
            this.EnrollmentOrders = new HashSet<EnrollmentOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<short> YearStart { get; set; }
        public Nullable<short> YearEnd { get; set; }
        public Nullable<int> CampaignStatusId { get; set; }
        public Nullable<int> CampaignTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionVolume> AdmissionVolumes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignIndividualAchievement> CampaignIndividualAchievements { get; set; }
        public virtual CampaignStatus CampaignStatus { get; set; }
        public virtual CampaignType CampaignTyp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetitiveGroup> CompetitiveGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntranceTest> EntranceTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentOrder> EnrollmentOrders { get; set; }
    }
}
