//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimCondition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClaimCondition()
        {
            this.EnrollmentAgreementClaims = new HashSet<EnrollmentAgreementClaim>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<int> CompetitiveGroupId { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> EnrollmentAgreementDate { get; set; }
        public Nullable<System.DateTime> EnrollmentDisclaimerDate { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual CompetitiveGroup CompetitiveGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentAgreementClaim> EnrollmentAgreementClaims { get; set; }
    }
}
