//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Claim()
        {
            this.ClaimConditions = new HashSet<ClaimCondition>();
            this.EgeDocuments = new HashSet<EgeDocument>();
            this.EntranceTestResults = new HashSet<EntranceTestResult>();
            this.Entrants = new HashSet<Entrant>();
            this.HighEducationDiplomaDocuments = new HashSet<HighEducationDiplomaDocument>();
            this.IdentityDocuments = new HashSet<IdentityDocument>();
            this.MiddleEducationDiplomaDocuments = new HashSet<MiddleEducationDiplomaDocument>();
            this.OrphanDocuments = new HashSet<OrphanDocument>();
            this.SchoolCertificateDocuments = new HashSet<SchoolCertificateDocument>();
            this.EntranceIndividualAchievements = new HashSet<EntranceIndividualAchievement>();
            this.OtherRequiredDocuments = new HashSet<OtherRequiredDocument>();
            this.EnrollmentClaims = new HashSet<EnrollmentClaim>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<bool> IsHostelNeed { get; set; }
        public Nullable<int> ClaimStatusId { get; set; }
        public string StatusComment { get; set; }
        public Nullable<bool> PersonalReturning { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> WorkOkStudentId { get; set; }
        public string AstuStudentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimCondition> ClaimConditions { get; set; }
        public virtual ClaimStatus ClaimStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EgeDocument> EgeDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntranceTestResult> EntranceTestResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrant> Entrants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HighEducationDiplomaDocument> HighEducationDiplomaDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdentityDocument> IdentityDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiddleEducationDiplomaDocument> MiddleEducationDiplomaDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrphanDocument> OrphanDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolCertificateDocument> SchoolCertificateDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntranceIndividualAchievement> EntranceIndividualAchievements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherRequiredDocument> OtherRequiredDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentClaim> EnrollmentClaims { get; set; }
    }
}
