//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitiveGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompetitiveGroup()
        {
            this.ClaimConditions = new HashSet<ClaimCondition>();
            this.CompetitionEntranceTests = new HashSet<CompetitionEntranceTest>();
            this.CompetitiveGroupItems = new HashSet<CompetitiveGroupItem>();
            this.EnrollmentProtocols = new HashSet<EnrollmentProtocol>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public string Name { get; set; }
        public Nullable<int> EducationLevelId { get; set; }
        public Nullable<int> FinanceSourceId { get; set; }
        public Nullable<int> EducationFormId { get; set; }
        public Nullable<int> DirectionId { get; set; }
        public Nullable<bool> IsAdditional { get; set; }
        public string RegistrationNumberMemberPart { get; set; }
        public Nullable<System.DateTime> AdmissionFirstStageEndDate { get; set; }
        public Nullable<System.DateTime> AdmissionSecondStageEndDate { get; set; }
        public Nullable<System.DateTime> AdmissionThirdStageEndDate { get; set; }
        public Nullable<int> EducationProgramTypeId { get; set; }
        public string ExportCode { get; set; }
        public Nullable<int> PlaceCount { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimCondition> ClaimConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetitionEntranceTest> CompetitionEntranceTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetitiveGroupItem> CompetitiveGroupItems { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual EducationForm EducationForm { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual FinanceSource FinanceSource { get; set; }
        public virtual EducationProgramType EducationProgramType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentProtocol> EnrollmentProtocols { get; set; }
    }
}
