//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributedAdmissionVolume
    {
        public int Id { get; set; }
        public Nullable<int> AdmissionVolumeId { get; set; }
        public Nullable<int> BudgetLevelId { get; set; }
        public Nullable<int> NumberBudgetO { get; set; }
        public Nullable<int> NumberBudgetZ { get; set; }
        public Nullable<int> NumberBudgetOZ { get; set; }
        public Nullable<int> NumberQuotaO { get; set; }
        public Nullable<int> NumberQuotaZ { get; set; }
        public Nullable<int> NumberQuotaOZ { get; set; }
        public Nullable<int> NumberTargetO { get; set; }
        public Nullable<int> NumberTargetZ { get; set; }
        public Nullable<int> NumberTargetOZ { get; set; }
    
        public virtual AdmissionVolume AdmissionVolume { get; set; }
        public virtual BudgetLevel BudgetLevel { get; set; }
    }
}
