//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationOrganization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EducationOrganization()
        {
            this.HighEducationDiplomaDocuments = new HashSet<HighEducationDiplomaDocument>();
            this.MiddleEducationDiplomaDocuments = new HashSet<MiddleEducationDiplomaDocument>();
            this.SchoolCertificateDocuments = new HashSet<SchoolCertificateDocument>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> EducationOrganizationTypeId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> AbituId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual EducationOrganizationType EducationOrganizationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HighEducationDiplomaDocument> HighEducationDiplomaDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiddleEducationDiplomaDocument> MiddleEducationDiplomaDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolCertificateDocument> SchoolCertificateDocuments { get; set; }
    }
}
