//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgeResult
    {
        public int Id { get; set; }
        public Nullable<int> EgeDocumentId { get; set; }
        public Nullable<int> ExamSubjectId { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<int> CheckProtocolId { get; set; }
    
        public virtual EgeDocument EgeDocument { get; set; }
        public virtual ExamSubject ExamSubject { get; set; }
        public virtual EntranceExaminationsCheckProtocol EntranceExaminationsCheckProtocol { get; set; }
    }
}
