//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentAgreementClaim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnrollmentAgreementClaim()
        {
            this.EnrollmentDisagreementClaims = new HashSet<EnrollmentDisagreementClaim>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClaimConditionId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ClaimCondition ClaimCondition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentDisagreementClaim> EnrollmentDisagreementClaims { get; set; }
    }
}
