//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnrollmentOrder()
        {
            this.EnrollmentExceptionOrders = new HashSet<EnrollmentExceptionOrders>();
            this.EnrollmentProtocols = new HashSet<EnrollmentProtocol>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<int> EducationFormId { get; set; }
        public Nullable<int> FinanceSourceId { get; set; }
        public Nullable<int> EducationLevelId { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual EducationForm EducationForm { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual FinanceSource FinanceSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentExceptionOrders> EnrollmentExceptionOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentProtocol> EnrollmentProtocols { get; set; }
    }
}
