//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentProtocol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnrollmentProtocol()
        {
            this.EnrollmentClaims = new HashSet<EnrollmentClaim>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> TrainingBeginDate { get; set; }
        public Nullable<System.DateTime> TrainingEndDate { get; set; }
        public string TrainingTime { get; set; }
        public Nullable<int> CompetitiveGroupId { get; set; }
        public Nullable<int> EnrollmentOrderId { get; set; }
        public Nullable<int> FacultyId { get; set; }
    
        public virtual CompetitiveGroup CompetitiveGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentClaim> EnrollmentClaims { get; set; }
        public virtual EnrollmentOrder EnrollmentOrder { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
