//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntrantContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntrantContract()
        {
            this.ContractIndividualPlanAuxAgreements = new HashSet<ContractIndividualPlanAuxAgreement>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EntrantId { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TrainingPeriod { get; set; }
        public Nullable<double> YearPrice { get; set; }
        public Nullable<double> FullPrice { get; set; }
        public Nullable<int> ContragentTypeId { get; set; }
        public Nullable<int> ContragentPersonId { get; set; }
        public Nullable<int> ContragentOrganizationId { get; set; }
    
        public virtual ContragentOrganization ContragentOrganization { get; set; }
        public virtual ContragentPerson ContragentPerson { get; set; }
        public virtual ContragentType ContragentType { get; set; }
        public virtual Entrant Entrant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractIndividualPlanAuxAgreement> ContractIndividualPlanAuxAgreements { get; set; }
    }
}
