//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntranceIndividualAchievement
    {
        public int Id { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<int> CampaignIndividualAchievementId { get; set; }
    
        public virtual CampaignIndividualAchievement CampaignIndividualAchievement { get; set; }
        public virtual Claim Claim { get; set; }
    }
}
