//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntranceTestResult
    {
        public int Id { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<int> EntranceTestId { get; set; }
        public Nullable<int> Value { get; set; }
        public string Variant { get; set; }
        public Nullable<int> ClassroomId { get; set; }
        public Nullable<int> TableLineNumber { get; set; }
        public Nullable<int> TablePlaceNumber { get; set; }
        public Nullable<int> PrimaryMark { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual EntranceTest EntranceTest { get; set; }
    }
}
