//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entrant()
        {
            this.EntrantContracts = new HashSet<EntrantContract>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string CustomInformation { get; set; }
        public string Email { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string FatherName { get; set; }
        public string FatherPhone { get; set; }
        public string FatherJob { get; set; }
        public string MotherName { get; set; }
        public string MotherPhone { get; set; }
        public string MotherJob { get; set; }
        public string JobPost { get; set; }
        public string JobOrganization { get; set; }
        public Nullable<decimal> JobStage { get; set; }
        public Nullable<int> ForeignLanguageId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Claim Claim { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ForeignLanguage ForeignLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntrantContract> EntrantContracts { get; set; }
    }
}
