//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceSource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinanceSource()
        {
            this.CompetitiveGroups = new HashSet<CompetitiveGroup>();
            this.EntranceTests = new HashSet<EntranceTest>();
            this.EnrollmentOrders = new HashSet<EnrollmentOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ExportCode { get; set; }
        public string NameInDocument { get; set; }
        public Nullable<int> SortNumber { get; set; }
        public string EnrollmentReason { get; set; }
        public Nullable<int> WorkOkId { get; set; }
        public string AstuId { get; set; }
        public string AstuIdKob { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetitiveGroup> CompetitiveGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntranceTest> EntranceTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentOrder> EnrollmentOrders { get; set; }
    }
}
