//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighEducationDiplomaDocument
    {
        public int Id { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<System.DateTime> OriginalReceivedDate { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SubdivisionCode { get; set; }
        public Nullable<int> EducationOrganizationId { get; set; }
        public Nullable<int> FiveCount { get; set; }
        public Nullable<int> FourCount { get; set; }
        public Nullable<int> ThreeCount { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual EducationOrganization EducationOrganization { get; set; }
    }
}
