//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityDocument
    {
        public int Id { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<System.DateTime> OriginalReceivedDate { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SubdivisionCode { get; set; }
        public string Organization { get; set; }
        public Nullable<int> IdenityDocumentTypeId { get; set; }
        public Nullable<int> CitizenshipId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
    
        public virtual Citizenship Citizenship { get; set; }
        public virtual Claim Claim { get; set; }
        public virtual IdentityDocumentType IdentityDocumentType { get; set; }
    }
}
