//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherCapitalCertificates
    {
        public int Id { get; set; }
        public string Series { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ReasonInfo { get; set; }
        public Nullable<int> ContragentId { get; set; }
    
        public virtual ContragentPerson ContragentPerson { get; set; }
    }
}
