//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherRequiredDocument
    {
        public int Id { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<bool> Fluorography { get; set; }
        public Nullable<bool> MedicinePermission { get; set; }
        public Nullable<bool> Photos { get; set; }
        public Nullable<bool> Certificate { get; set; }
    
        public virtual Claim Claim { get; set; }
    }
}
