//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Admission
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentGroup()
        {
            this.ClaimStudentGroupRelationships = new HashSet<ClaimStudentGroupRelationship>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> GroupFormingOrderId { get; set; }
        public Nullable<int> WorkOkId { get; set; }
        public string AstuId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public string PlanId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimStudentGroupRelationship> ClaimStudentGroupRelationships { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual GroupFormingOrder GroupFormingOrder { get; set; }
    }
}
